apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: push-task
  namespace: cicd
spec:
  workspaces:
  - name: dockerImageArtefact
  params:
    - name: imageName
      type: string
      description: The name of the docker image
      default: alpinehelloworld
  steps:
    - name: push
      image: docker
      command:
        - sh
        - -c
        - "
          docker login --username jimcarl91 --password dckr_pat_bYLZiA-j9mjq2i5I5xUf8PUQxuM && \
          docker load < $(workspaces.dockerImageArtefact.path)/$(params.imageName).tar && \
          docker tag $(params.imageName) jimcarl91/$(params.imageName) && \
          docker push jimcarl91/$(params.imageName)
          "
      securityContext:
        privileged: true
      volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
